RESPONSES = {
    1: 'Strongly Disagree',
    2: 'Disagree',
    3: 'Agree',
    4: 'Strongly Agree'
}

ALIGNMENTS = {
    1: 'Far left',
    2: 'Left',
    3: 'Moderately left',
    4: 'Neither',
    5: 'Moderately right',
    6: 'Right',
    7: 'Far right'
}

QUESTIONS = [
    "Hierarchies will inevitably be formed in every society.",
    "We are living in a post-modern age with no discernible 'true' reality.",
    "A truly democratic system is unrealistic.",
    "The penal system is designed to protect the interests of the ruling class.",
    "We must retain the core constitutional principles of our institutions.",
    "The traditions of law and justice in my community must be greatly respected.",
    "We should not question sovereign authority so long as it provides peace.",
    "A society that promotes equal outcomes for all is desirable.",
    "The traditional family is, unfortunately, the embodiment of an authoritarian personality and, ultimately, fascism.",
    "There is no grand tradition of anything only various competing claims.",
    "We have no transcendent purpose beyond our own material pleasure.",
    "Collective obligations that are placed on an individual by society are inherently immoral.",
    "Corruption and decay is an 'iron law' of human societies.",
    "Humanity only experiences linear growth - not decay.",
    "Societies develop through a cooperative social contract.",
    "The concepts of 'good' and 'evil' are subjective.",
    "The industrial revolution and its consequences have been largely negative.",
    "People should be treated equally regardless of their social group.",
    "Technological development has brought about a better world.",
    "To ground any coherent worldview one needs higher spiritual values.",
    "Religion is merely a distraction from the material world.",
    "Language developed as a tool to dominate and exclude 'the other'.",
    "Human society should be viewed through a pessimistic lens.",
    "Societies of vulnerability will always defeat societies of exclusion.",
    "A liberal democracy is the final stage in societal development.",
    "There is more to this world than the purely physical.",
    "All people possess a soul.",
    "History can be understood as a great march of progress.",
    "Human nature is nasty, brutish and short, it must be repressed by society.",
    "We are defined morally, at least in part, by our actions.",
    "If a society is not grounded by ancestral traditions it will fall into chaos.",
    "We should strive to eliminate social biases toward minority groups.",
    "Humanity can be relied on to self-regulate and self-reform.",
    "We are currently in the dark age of human flourishing.",
    "A collective founded on absolute values will always outlive those founded on relative values.",
    "Without a constraining force society will always tend towards immorality.",
    "It is better to die standing than to live on one's knees.",
    "All institutions are biased towards their own cultural background.",
    "No institution can be truly egalitarian.",
    "Without God and higher ideals institutions will collapse.",
    "Some people will always be more successful than others.",
    "Our modern world is progressing towards a utopia.",
    "Man's natural state is egalitarian and pacifistic.",
    "We can best pursue meaning by living disciplined and virtuous lives.",
    "Different combinations of social identities produce unique forms of disadvantage and oppression.",
    "Science and rationality are best when it comes to describing our world.",
    "There is more to life than the pursuit of pleasure.",
    "Liberation of the individual from all arbitrary boundaries (race, gender, etc.) is ideal.",
    "Social relations should be understood, primarily, as expressions of tyrannical power.",
    "Societies tend toward immorality and, as such, they require a strong leader to maintain order.",
    "Society will always consist of rulers and subjects.",
    "The ideas of progress and rationality are symptoms of societal decline.",
    "Every civilization goes through a birth, a rise and a fall.",
    "The most successful people are those who are the most deserving of their success.",
    "Individuals have a duty towards upholding the collective good.",
    "Societal hierarchies often come about through the oppression of disadvantaged groups.",
    "Direct or pure democracy is the ideal form of government.",
    "An action is generally good if its consequences are good.",
    "Peaceful societies are rare and fragile.",
    "Through sexual exploration and liberation we can escape the societies of control."
]
